const CATEGORIES_PARSER = [
  { title: { eng: 'Decks', ua: 'Дошки' }, value: 'decks' },
  { title: 'Trucks', value: 'trucks' },
  { title: 'Wheels', value: 'wheels' },
  { title: 'Other', value: 'other' },
  { title: 'Completes', value: 'completes' },
  { title: 'Leather', value: 'leather' },
  { title: 'Seude', value: 'seude' },
  { title: 'Canvas', value: 'canvas' },
  { title: 'Shoes', value: 'shoes' },
  { title: 'Barely used', value: 'barely' },
  { title: 'New', value: 'new' },
  { title: 'Roughly', value: 'roughly' },
  { title: 'Skates', value: 'skateboards' },
];
const BRANDS = [
  'Baker',
  '5Boro',
  'Alien Workshop',
  'Alltimers',
  'Almost',
  'Anti Hero',
  'April',
  'Bacon',
  'Birdhouse',
  'Blueprint',
  'Chocolate',
  'Creature',
  'Darkroom',
  'Darkstar',
  'Deathwish',
  'DGK',
  'Dogtown',
  'Element',
  'Enjoi',
  'Flip',
  'Foundation',
  'Frog',
  'Girl',
  'Globe',
  'Habitat',
  'Heroin',
  'HUF',
  'Killing Floor',
  'Krooked',
  'Lovesick',
  'Madness',
  'Magenta',
  'Meow',
  'Metal',
  'Mini Logo',
  'Monarch Project',
  'Piss Drunx',
  'Plan B',
  'Polar',
  'Powell',
  'Primitive',
  'Quasi',
  'Real',
  'Santa Cruz',
  "Shorty's",
  'Sk8 Mafia',
  'Skate Warehouse',
  'StrangeLove',
  'Suicidal Skates',
  'Thank You',
  'The Heart Supply',
  'The Heated Wheel',
  'Theories',
  'There',
  'Toy Machine',
  'Transportation Unit',
  'Uma Landsleds',
  'Unity',
  'Verb',
  'Welcome',
  'WKND',
  'Zero',
  'Ace',
  'Bullet',
  'Independent',
  'Krux',
  'Royal',
  'Slappy',
  'Tensor',
  'Thunder',
  'Venture',
  'Bones Wheels',
  'Blind',
  'OJ',
  'Portland Wheel Company',
  'Ricta',
  'Satori',
  'Slime Balls',
  'Snot',
  'Spitfire',
  'Vol. 1',
  'Bones Bearings',
  'Andale',
  'Black Panther',
  'Bronson Speed Co.',
  'Cortina Bearing Co.',
  'Modus',
  'Shake Junt',
  'SKF',
  'Speed Demons',
  'Adidas',
  'Converse Skateboarding',
  'DC',
  'Emerica',
  'eS',
  'Fallen',
  'Lakai',
  'Last Resort AB',
  'New Balance Numeric',
  'Nike SB',
  'Vans',
  'Volcom',
];
export { CATEGORIES_PARSER, BRANDS };
